export const GITHUB = {
  API_URL: process.env.REACT_APP_GITHUB_API_URL,
  GRAPHQL_API_URL: process.env.REACT_APP_GITHUB_GRAPHQL_API_URL,
  GRAPHQL_API_TOKEN: process.env.REACT_APP_GITHUB_GRAPHQL_TOKEN,
};
